version: "3.9"
services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./volume/mongo:/data/db
    ports:
      - 27017:27017
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./:/app
    network_mode: "host"
    depends_on:
      - "mongo"
