version: "3.9"
services:
  
  mqtt:
    image: eclipse-mosquitto

  mongo:
    image: mongo:4.4
    volumes:
      - mongo:/data/db
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./:/app
    ports:
      - 3000:3000    
    depends_on:
      - "mqtt"
      - "mongo"

volumes:
  mongo:
    name: mongo