version: "3.9"
services:
  mongo:
    image: bitnami/mongodb:latest
    volumes:
      - ./volume/mongo:/bitnami/mongodb
    ports:
      - 27017:27017
  web:
    build: .
    volumes:
      - ./:/app
    network_mode: "host"
    depends_on:
      - "mongo"
